export const mockTechnicians = [
	{ id: 'u1', name: 'John Smith', role: 'Senior Technician', avatar: 'JS', email: 'john.smith@company.com', activeTickets: 3 },
	{ id: 'u2', name: 'Sarah Johnson', role: 'Network Specialist', avatar: 'SJ', email: 'sarah.johnson@company.com', activeTickets: 5 },
	{ id: 'u3', name: 'Mike Chen', role: 'System Administrator', avatar: 'MC', email: 'mike.chen@company.com', activeTickets: 2 },
	{ id: 'u4', name: 'Lisa Rodriguez', role: 'Security Analyst', avatar: 'LR', email: 'lisa.rodriguez@company.com', activeTickets: 4 },
]

export const mockTicketCategories = [
	{ id: 'infrastructure', name: 'Infrastructure', color: 'blue', icon: '🏗️' },
	{ id: 'network', name: 'Network', color: 'green', icon: '🌐' },
	{ id: 'software', name: 'Software', color: 'purple', icon: '💻' },
	{ id: 'security', name: 'Security', color: 'red', icon: '🔒' },
	{ id: 'database', name: 'Database', color: 'orange', icon: '🗄️' },
	{ id: 'hardware', name: 'Hardware', color: 'gray', icon: '⚙️' },
]

export const mockTickets = [
	{ 
		id: 'TKT-001', 
		title: 'Email server down', 
		priority: 'high', 
		status: 'resolved', 
		category: 'infrastructure', 
		client: 'Acme Corp',
		clientId: 'c1',
		createdAt: '2024-01-15T09:30:00Z', 
		updatedAt: '2024-01-15T14:45:00Z',
		resolvedAt: '2024-01-15T14:45:00Z',
		assignedTo: 'u1', 
		timeSpent: 2.5, 
		estimatedTime: 3.0,
		description: 'Exchange server is not responding. Users cannot send or receive emails.',
		slaTarget: '2024-01-15T13:30:00Z',
		slaStatus: 'breached',
		tags: ['critical', 'email', 'server'],
		satisfaction: 4.5,
		resolutionNotes: 'Restarted Exchange services and cleared message queue'
	},
	{ 
		id: 'TKT-002', 
		title: 'VPN connection issues', 
		priority: 'medium', 
		status: 'in_progress', 
		category: 'network', 
		client: 'TechStart Inc',
		clientId: 'c2',
		createdAt: '2024-02-10T11:15:00Z', 
		updatedAt: '2024-02-10T15:30:00Z',
		assignedTo: 'u2', 
		timeSpent: 1.5, 
		estimatedTime: 2.0,
		description: 'Multiple users reporting VPN connection timeouts and authentication failures.',
		slaTarget: '2024-02-11T11:15:00Z',
		slaStatus: 'on_track',
		tags: ['vpn', 'authentication', 'network'],
		satisfaction: null
	},
	{ 
		id: 'TKT-003', 
		title: 'Software installation request', 
		priority: 'low', 
		status: 'open', 
		category: 'software', 
		client: 'RetailMax',
		clientId: 'c3',
		createdAt: '2024-03-05T14:20:00Z', 
		updatedAt: '2024-03-05T14:20:00Z',
		assignedTo: null, 
		timeSpent: 0.0, 
		estimatedTime: 1.0,
		description: 'Need to install new accounting software on 5 workstations.',
		slaTarget: '2024-03-08T14:20:00Z',
		slaStatus: 'on_track',
		tags: ['installation', 'accounting', 'workstation'],
		satisfaction: null
	},
	{ 
		id: 'TKT-004', 
		title: 'Critical security patch deployment', 
		priority: 'critical', 
		status: 'resolved', 
		category: 'security', 
		client: 'HealthCare Plus',
		clientId: 'c4',
		createdAt: '2024-03-12T08:00:00Z', 
		updatedAt: '2024-03-12T10:30:00Z',
		resolvedAt: '2024-03-12T10:30:00Z',
		assignedTo: 'u4', 
		timeSpent: 1.5, 
		estimatedTime: 2.0,
		description: 'Critical Windows security patch needs immediate deployment across all servers.',
		slaTarget: '2024-03-12T12:00:00Z',
		slaStatus: 'met',
		tags: ['security', 'patch', 'windows', 'critical'],
		satisfaction: 5.0,
		resolutionNotes: 'Successfully deployed patches to all 15 servers with no downtime'
	},
	{ 
		id: 'TKT-005', 
		title: 'Database performance optimization', 
		priority: 'medium', 
		status: 'in_progress', 
		category: 'database', 
		client: 'FinanceFirst',
		clientId: 'c5',
		createdAt: '2024-03-20T13:45:00Z', 
		updatedAt: '2024-03-21T16:00:00Z',
		assignedTo: 'u3', 
		timeSpent: 4.5, 
		estimatedTime: 6.0,
		description: 'Database queries are running slowly, affecting application performance.',
		slaTarget: '2024-03-22T13:45:00Z',
		slaStatus: 'at_risk',
		tags: ['database', 'performance', 'optimization'],
		satisfaction: null
	},
	{ 
		id: 'TKT-006', 
		title: 'Printer connectivity issues', 
		priority: 'low', 
		status: 'open', 
		category: 'hardware', 
		client: 'Acme Corp',
		clientId: 'c1',
		createdAt: '2024-03-22T10:15:00Z', 
		updatedAt: '2024-03-22T10:15:00Z',
		assignedTo: 'u1', 
		timeSpent: 0.0, 
		estimatedTime: 0.5,
		description: 'Office printer not responding to print jobs from workstations.',
		slaTarget: '2024-03-25T10:15:00Z',
		slaStatus: 'on_track',
		tags: ['printer', 'connectivity', 'hardware'],
		satisfaction: null
	},
	{ 
		id: 'TKT-007', 
		title: 'Backup system failure', 
		priority: 'high', 
		status: 'open', 
		category: 'infrastructure', 
		client: 'TechStart Inc',
		clientId: 'c2',
		createdAt: '2024-03-23T07:30:00Z', 
		updatedAt: '2024-03-23T09:15:00Z',
		assignedTo: 'u3', 
		timeSpent: 0.5, 
		estimatedTime: 3.0,
		description: 'Nightly backup job failed for the past 3 days. Need immediate investigation.',
		slaTarget: '2024-03-23T15:30:00Z',
		slaStatus: 'at_risk',
		tags: ['backup', 'failure', 'critical'],
		satisfaction: null
	},
	{ 
		id: 'TKT-008', 
		title: 'User access provisioning', 
		priority: 'medium', 
		status: 'resolved', 
		category: 'security', 
		client: 'RetailMax',
		clientId: 'c3',
		createdAt: '2024-03-21T12:00:00Z', 
		updatedAt: '2024-03-22T14:30:00Z',
		resolvedAt: '2024-03-22T14:30:00Z',
		assignedTo: 'u4', 
		timeSpent: 1.0, 
		estimatedTime: 1.0,
		description: 'New employee needs access to file shares and applications.',
		slaTarget: '2024-03-22T12:00:00Z',
		slaStatus: 'breached',
		tags: ['access', 'provisioning', 'new-user'],
		satisfaction: 4.0,
		resolutionNotes: 'Created user account and assigned appropriate permissions'
	}
]

export const mockTimeEntries = {
	'TKT-001': [ { at: '2024-01-15 10:00', technician: 'u3', hours: 2.5, note: 'Diagnosed and restarted services' } ],
	'TKT-002': [ { at: '2024-02-10 12:00', technician: 'u3', hours: 1.0, note: 'Fixed firewall rule' } ],
	'TKT-003': [],
	'TKT-004': [ { at: '2024-03-12 09:30', technician: 'u3', hours: 1.5, note: 'Applied patch, verified' } ],
	'TKT-005': [ { at: '2024-03-20 11:00', technician: 'u3', hours: 2.0, note: 'Index tuning' }, { at: '2024-03-21 14:00', technician: 'u3', hours: 1.0, note: 'Monitoring' } ],
}
